[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/curriculum"
  to = "/curriculum.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
